# Generated by Django 2.2 on 2023-08-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('ProfilePicture', models.ImageField(upload_to='profile_photo')),
                ('UserName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Address', models.CharField(max_length=255)),
                ('UserType', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('ConfirmPassword', models.CharField(max_length=255)),
            ],
        ),
    ]
