# Generated by Django 2.2 on 2023-08-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20230820_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Image',
            new_name='Images',
        ),
    ]
