# Generated by Django 2.2 on 2023-08-20 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20230820_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Images',
            field=models.ImageField(upload_to='uploadBlog'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='IsDraft',
            field=models.CharField(max_length=250),
        ),
    ]
