# Generated by Django 2.2 on 2023-08-20 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20230820_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Images',
            new_name='BlogImages',
        ),
    ]
