# Generated by Django 2.2 on 2023-08-20 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20230820_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogImages',
            field=models.FileField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ProfilePicture',
            field=models.FileField(upload_to='media'),
        ),
    ]
