# Generated by Django 2.2 on 2023-08-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20230820_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogImages',
            field=models.FileField(upload_to='blogfile'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ProfilePicture',
            field=models.FileField(upload_to='profilepicture'),
        ),
    ]
