# Generated by Django 2.2 on 2023-08-20 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_auto_20230820_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='IsDraft',
            field=models.BooleanField(default=False),
        ),
    ]
