# Generated by Django 2.2 on 2023-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_auto_20230821_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='BlogImages',
            field=models.FileField(upload_to='profilepicture'),
        ),
    ]
